
namespace EngineeringCollegeApp
{
    enum Branches
    {
        COMPUTER_ENGINEERING, INFORMATION_TECHNOLOGY_ENGINEERING, EXTC_ENGINEERING, ETRX_ENGINEERING,
        INSTRUMENTATION_ENGINEERING, CHEMICAL_ENGINEERING
    }
}
